version: "3.9"
services:
  api:
    build: .
    container_name: idiompace_api
    ports:
      - "4021:4001"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: postgres:17.4
    container_name: postgres_idiompace
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/PostgreSQL/icon.png
    restart: always
    ports:
      - "5434:5432"   # Puerto externo 5434 → interno 5432
    env_file:
      - .env  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
